export const profileCatalog = [
  {
    id: 'profile_diplomat',
    code: 'diplomat',
    name: 'Diplomate',
    description:
      "Vous créez des ponts entre les personnes et favorisez l'harmonie dans les environnements complexes.",
    strengths: ['Ecoute active', 'Mediation', "Esprit d'equipe", 'Adaptation sociale'],
    weaknesses: ['Evite parfois les conflits', 'Difficulte a dire non', 'Peut se suradapter'],
    recommended_careers: ['RH', 'Mediateur', 'Coach', 'Relations publiques'],
    advice: ['Posez des limites claires', "Pratiquez l'assertivite", 'Affrontez les tensions utiles'],
    dominant_traits: { collaboration: 3, emotional: 2, communication: 2, introversion: 1 },
    color: '#14B8A6',
    theme: { from: '#0EA5E9', to: '#14B8A6' },
  },
  {
    id: 'profile_analyst',
    code: 'analyst',
    name: 'Analyste',
    description:
      'Vous structurez les decisions avec rigueur et transformez les signaux faibles en choix fiables.',
    strengths: ['Rigueur', 'Esprit critique', 'Resolution de probleme', 'Precision'],
    weaknesses: ['Perfectionnisme', 'Sur-analyse', 'Expression emotionnelle reservee'],
    recommended_careers: ['Data analyst', 'Consultant', 'Ingenieur', 'Audit'],
    advice: ['Validez vite avec des tests', "Integrez l'intuition terrain", 'Partagez vos conclusions simplement'],
    dominant_traits: { analytical: 3, rational: 3, discipline: 2, introversion: 1 },
    color: '#3B82F6',
    theme: { from: '#1D4ED8', to: '#3B82F6' },
  },
  {
    id: 'profile_leader',
    code: 'leader',
    name: 'Leader',
    description:
      'Vous mobilisez les autres, donnez une direction claire et avancez avec energie dans les situations floues.',
    strengths: ['Prise de decision', 'Vision', 'Influence', 'Capacite a trancher'],
    weaknesses: ['Impatience', 'Delegation parfois limitee', 'Controle excessif'],
    recommended_careers: ['Management', 'Entrepreneuriat', 'Direction de projet', 'Operations'],
    advice: ['Deleguez avec confiance', "Demandez du feedback regulier", 'Gardez un rythme soutenable'],
    dominant_traits: { leadership: 3, extraversion: 2, rational: 2, communication: 2 },
    color: '#F97316',
    theme: { from: '#EA580C', to: '#FB923C' },
  },
  {
    id: 'profile_creative',
    code: 'creative',
    name: 'Créatif',
    description:
      'Vous imaginez des angles originaux et transformez les contraintes en opportunites concrètes.',
    strengths: ['Innovation', 'Souplesse mentale', 'Vision produit', 'Curiosite'],
    weaknesses: ['Dispersion', 'Priorisation variable', 'Execution inegale'],
    recommended_careers: ['Design', 'Marketing', 'Creation de contenu', 'Produit'],
    advice: ['Cadrez vos idees en cycles courts', 'Mesurez vos hypotheses', 'Conservez du temps de focus'],
    dominant_traits: { creative: 3, intuition: 2, adaptability: 2, emotional: 1 },
    color: '#8B5CF6',
    theme: { from: '#7C3AED', to: '#A78BFA' },
  },
  {
    id: 'profile_empathetic',
    code: 'empathetic',
    name: 'Empathique',
    description:
      'Vous captez rapidement les besoins humains et creez de la confiance durable autour de vous.',
    strengths: ['Empathie', 'Soutien', 'Communication', 'Cohesion'],
    weaknesses: ['Charge emotionnelle', 'Difficulte a se proteger', 'Decision parfois differee'],
    recommended_careers: ['Psychologie', 'Education', 'UX research', 'Customer success'],
    advice: ['Proteger votre energie', 'Formaliser les priorites', 'Alterner ecoute et action'],
    dominant_traits: { emotional: 3, collaboration: 2, communication: 2, adaptability: 1 },
    color: '#EC4899',
    theme: { from: '#DB2777', to: '#F472B6' },
  },
  {
    id: 'profile_logical',
    code: 'logical',
    name: 'Logique',
    description:
      'Vous cherchez la coherence, simplifiez les systemes et optimisez les processus avec pragmatisme.',
    strengths: ['Structuration', 'Clarte', 'Fiabilite', 'Priorisation'],
    weaknesses: ['Rigidite possible', 'Prise de recul emotionnelle', 'Marge creative reduite'],
    recommended_careers: ['Architecture logicielle', 'Finance', 'Ops', 'Qualite'],
    advice: ['Gardez un espace exploratoire', 'Verifiez les impacts humains', 'Utilisez des revues contradictoires'],
    dominant_traits: { rational: 3, analytical: 2, discipline: 2, introversion: 1 },
    color: '#475569',
    theme: { from: '#334155', to: '#64748B' },
  },
  {
    id: 'profile_introvert',
    code: 'introvert',
    name: 'Introverti',
    description:
      'Vous excellez dans la profondeur, la concentration et la qualite de reflexion sur des sujets complexes.',
    strengths: ['Concentration', 'Autonomie', 'Ecoute', 'Profondeur analytique'],
    weaknesses: ['Visibilite reduite', 'Rythme social plus faible', 'Prise de parole selective'],
    recommended_careers: ['Recherche', 'Developpement', 'Redaction', 'Analyse strategique'],
    advice: ['Rendez visible votre impact', 'Planifiez des interactions cles', 'Protegez vos plages de focus'],
    dominant_traits: { introversion: 3, analytical: 2, discipline: 2, rational: 1 },
    color: '#6366F1',
    theme: { from: '#4F46E5', to: '#818CF8' },
  },
  {
    id: 'profile_extrovert',
    code: 'extrovert',
    name: 'Extraverti',
    description:
      'Vous gagnez en energie dans le collectif et savez declencher rapidement de la dynamique.',
    strengths: ['Influence sociale', 'Energie', 'Networking', 'Initiative'],
    weaknesses: ['Impulsivite', 'Ecoute parfois partielle', 'Surcharge de contexte'],
    recommended_careers: ['Vente', 'Business development', 'Evenementiel', 'Community'],
    advice: ['Cadrez vos priorites', 'Laissez des temps de synthese', 'Consolidez vos suivis'],
    dominant_traits: { extraversion: 3, leadership: 2, communication: 2, adaptability: 1 },
    color: '#0EA5E9',
    theme: { from: '#0284C7', to: '#38BDF8' },
  },
  {
    id: 'profile_strategist',
    code: 'strategist',
    name: 'Stratège',
    description:
      'Vous combinez vision long terme et execution methodique pour atteindre des objectifs ambitieux.',
    strengths: ['Vision globale', 'Planification', 'Arbitrage', 'Anticipation'],
    weaknesses: ['Exigence elevee', 'Distance relationnelle possible', 'Risque de sur-optimisation'],
    recommended_careers: ['Strategie', 'Produit', 'Conseil', 'Direction transformation'],
    advice: ['Rythmez la strategie par des jalons', 'Partagez la logique de vos choix', 'Testez plus tot'],
    dominant_traits: { leadership: 2, analytical: 2, rational: 2, discipline: 2 },
    color: '#22C55E',
    theme: { from: '#16A34A', to: '#4ADE80' },
  },
  {
    id: 'profile_visionary',
    code: 'visionary',
    name: 'Visionnaire',
    description:
      'Vous detectez les evolutions futures, inspirez une direction nouvelle et alignez les energies.',
    strengths: ['Projection', 'Intuition', 'Narratif', 'Capacite a inspirer'],
    weaknesses: ['Execution detaillee variable', 'Risque de dispersion', 'Priorisation mouvante'],
    recommended_careers: ['Innovation', 'Produit', 'Entrepreneuriat', 'Direction creative'],
    advice: ['Ancrez la vision en preuves', 'Construisez un noyau operationnel', 'Cadencez les revues de trajectoire'],
    dominant_traits: { intuition: 3, creative: 2, leadership: 2, adaptability: 2 },
    color: '#A855F7',
    theme: { from: '#9333EA', to: '#C084FC' },
  },
];
